# Generated by Django 4.1.1 on 2022-10-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakultas', '0003_akreditasifkip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akreditasifkip',
            name='nilai',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
