# Generated by Django 4.1.1 on 2022-10-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakultas', '0005_dutafkip_matakuliahfkip_prodifkip_ruanganfkip_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dutafkip',
            old_name='nilai',
            new_name='nama',
        ),
        migrations.RenameField(
            model_name='matakuliahfkip',
            old_name='nilai',
            new_name='nama',
        ),
        migrations.RenameField(
            model_name='prodifkip',
            old_name='nilai',
            new_name='nama',
        ),
        migrations.RenameField(
            model_name='ruanganfkip',
            old_name='nilai',
            new_name='nomor',
        ),
        migrations.RenameField(
            model_name='ukmfkip',
            old_name='nilai',
            new_name='nama',
        ),
        migrations.AddField(
            model_name='dutafkip',
            name='nomor',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='matakuliahfkip',
            name='nomor',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='prodifkip',
            name='nomor',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='ruanganfkip',
            name='nama',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ukmfkip',
            name='nomor',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
